# Site settings
title: Michael G. Lobel
email: mglobel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lead developer at MyTennisLessons.com and traveling freelancer. Feel free to
  contact me about my work or to inquire about starting a project with me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mglobel.com" # the base hostname & protocol for your site
twitter_username: ringmylobel
github_username:  mglobel

# Build settings
markdown: kramdown
